# Generated by Django 5.1.4 on 2025-03-19 10:17

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('read', models.BooleanField(default=False)),
                ('date_modified', models.DateTimeField(auto_now_add=True, verbose_name=django.contrib.auth.models.User)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_author', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Zawiadomienia',
                'ordering': ['-date_modified'],
            },
        ),
    ]
