# Generated by Django 5.1.4 on 2025-03-04 21:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_full_name', models.CharField(max_length=255)),
                ('shipping_email', models.CharField(max_length=255)),
                ('shipping_street', models.CharField(default='', max_length=255)),
                ('shipping_house_number', models.CharField(default='', max_length=5)),
                ('shipping_flat_number', models.IntegerField(blank=True, null=True)),
                ('shipping_city', models.CharField(default='', max_length=120)),
                ('shipping_postal_code', models.CharField(default='', max_length=6)),
                ('shipping_province', models.CharField(default='', max_length=32)),
                ('shipping_voivodeship', models.CharField(default='', max_length=32)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Adres wysyłki',
            },
        ),
    ]
