# Generated by Django 5.1.4 on 2025-03-04 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=120, null=True)),
                ('company_nip', models.CharField(blank=True, max_length=20, null=True)),
                ('company_street', models.CharField(blank=True, max_length=255, null=True)),
                ('company_house_number', models.CharField(blank=True, max_length=5, null=True)),
                ('company_flat_number', models.IntegerField(blank=True, null=True)),
                ('company_city', models.CharField(blank=True, max_length=120, null=True)),
                ('company_postal_code', models.CharField(blank=True, max_length=6, null=True)),
                ('company_province', models.CharField(blank=True, max_length=32, null=True)),
                ('company_voivodeship', models.CharField(blank=True, max_length=32, null=True)),
            ],
        ),
    ]
