# Generated by Django 5.1.4 on 2025-03-06 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kasa', '0002_invoicedetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='shipping_street',
            new_name='shipping_house_and_street_no',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='shipping_flat_number',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='shipping_house_number',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='shipping_province',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='shipping_voivodeship',
        ),
    ]
