# Generated by Django 5.1.4 on 2025-03-06 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasa', '0003_rename_shipping_street_shippingaddress_shipping_house_and_street_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='shipping_email',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
