# Generated by Django 5.1.4 on 2025-03-06 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasa', '0004_alter_shippingaddress_shipping_email'),
        ('rynek', '0009_rename_street_profile_house_and_street_no_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_full_name', models.CharField(max_length=255)),
                ('order_email', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('order_shipping_address', models.TextField(default='', max_length=255254)),
                ('order_amount_paid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('order_date_ordered', models.DateTimeField(auto_now_add=True)),
                ('order_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items_quantity', models.PositiveBigIntegerField(default=1)),
                ('items_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('items_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kasa.order')),
                ('items_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rynek.product')),
                ('items_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
