# Generated by Django 5.1.4 on 2025-03-07 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasa', '0005_order_orderitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='shipping_full_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
