# Generated by Django 5.1.4 on 2025-03-07 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasa', '0006_alter_shippingaddress_shipping_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='shipping_country',
            field=models.CharField(default='Polska', max_length=255),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='shipping_city',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='shipping_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='shipping_full_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='shipping_house_and_street_no',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='shipping_postal_code',
            field=models.CharField(max_length=6),
        ),
    ]
