# Generated by Django 5.1.4 on 2025-03-07 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasa', '0008_order_order_shipping_method_shippingmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingmethod',
            name='shipping_time',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
