# Generated by Django 5.1.4 on 2025-03-07 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kasa', '0010_delete_shippingmethod'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoicedetails',
            options={'verbose_name_plural': 'Dane do faktury'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name_plural': 'Zamówienie'},
        ),
        migrations.AlterModelOptions(
            name='orderitems',
            options={'verbose_name_plural': 'Szczegóły zamówienia'},
        ),
    ]
