# Generated by Django 5.1.4 on 2025-03-08 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasa', '0011_alter_invoicedetails_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('methods', models.IntegerField(choices=[(1, 'Odbiór osobisty'), (2, 'Kurier'), (3, 'Poczta')], default=2, max_length=2)),
            ],
        ),
    ]
