# Generated by Django 5.1.4 on 2025-03-08 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasa', '0013_alter_shippingmethod_methods'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingmethod',
            name='price',
            field=models.IntegerField(choices=[(1, '0'), (2, '15.99'), (3, '4.39')], default=2),
        ),
        migrations.AddField(
            model_name='shippingmethod',
            name='time',
            field=models.IntegerField(choices=[(1, '0'), (2, '1-2'), (3, '2-4')], default=2),
        ),
        migrations.AlterField(
            model_name='shippingmethod',
            name='methods',
            field=models.IntegerField(choices=[(1, 'Odbiór osobisty'), (2, 'Kurier'), (3, 'Poczta')], default=2),
        ),
    ]
