# Generated by Django 5.1.4 on 2025-03-08 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasa', '0014_shippingmethod_price_shippingmethod_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_shipping_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kasa.shippingmethod'),
        ),
    ]
