# Generated by Django 5.1.4 on 2025-03-08 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasa', '0015_alter_order_order_shipping_method'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shippingmethod',
            options={'verbose_name_plural': 'Metody dostawy'},
        ),
        migrations.AlterField(
            model_name='shippingmethod',
            name='price',
            field=models.IntegerField(choices=[(1, '0,00'), (2, '15,99'), (3, '4,39')], default=2),
        ),
    ]
