# Generated by Django 5.1.4 on 2025-03-08 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasa', '0016_alter_shippingmethod_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingmethod',
            name='price',
            field=models.IntegerField(choices=[(1, '0'), (2, '15.99'), (3, '4.39')], default=2),
        ),
    ]
