# Generated by Django 5.1.4 on 2025-03-10 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasa', '0018_shippingmethod_user_alter_shippingmethod_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_name', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name_plural': 'Metody płatności',
            },
        ),
    ]
