# Generated by Django 5.1.4 on 2025-03-12 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kasa', '0019_paymentmethods'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_shipping_method',
        ),
    ]
