# Generated by Django 5.1.4 on 2025-03-12 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasa', '0020_remove_order_order_shipping_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_date_shipped',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_shipped',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_shipping_method',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='kasa.shippingmethod'),
        ),
    ]
