# Generated by Django 5.1.4 on 2025-03-12 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasa', '0022_alter_order_order_shipping_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_shipping_method',
            field=models.CharField(max_length=255),
        ),
    ]
