# Generated by Django 5.1.4 on 2025-03-14 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasa', '0023_alter_order_order_shipping_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_shipped',
            field=models.BooleanField(default=False),
        ),
    ]
