# Generated by Django 5.1.4 on 2025-02-17 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rynek', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='postal_code',
            field=models.CharField(default='', max_length=6),
        ),
        migrations.AddField(
            model_name='address',
            name='province',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='address',
            name='voivodeship',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='customer',
            name='regon',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='rynek.address'),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='address',
            name='house_number',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='customer',
            name='nip',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
