# Generated by Django 5.1.4 on 2025-02-18 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rynek', '0002_address_postal_code_address_province_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='title',
        ),
    ]
