# Generated by Django 5.1.4 on 2025-02-19 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rynek', '0003_alter_category_options_rename_name_product_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_on_sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='price_on_sale',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
