# Generated by Django 5.1.4 on 2025-02-28 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rynek', '0003_alter_category_slug_alter_subcategory_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
