# Generated by Django 5.1.4 on 2025-03-04 10:33

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rynek', '0004_subcategory_image_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='company',
            new_name='company_name',
        ),
        migrations.AddField(
            model_name='profile',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, verbose_name=django.contrib.auth.models.User),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_company',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='old_cart',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
