# Generated by Django 5.1.4 on 2025-02-19 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rynek', '0004_product_is_on_sale_product_price_on_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(default='Kilogram', max_length=120),
        ),
    ]
