# Generated by Django 5.1.4 on 2025-03-04 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rynek', '0005_rename_company_profile_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='old_cart',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
