# Generated by Django 5.1.4 on 2025-02-25 12:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rynek', '0006_remove_customer_address_differs_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Seller',
            new_name='Profile',
        ),
    ]
