# Generated by Django 5.1.4 on 2025-03-04 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rynek', '0006_alter_profile_old_cart'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Adres użytkownika'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Kategorie'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name_plural': 'Klienci'},
        ),
        migrations.AlterModelOptions(
            name='featuredproducts',
            options={'verbose_name_plural': 'Sponsorowane produkty'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name_plural': 'Zamówienia'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'Produkty'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name_plural': 'Profile użytkowników'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name_plural': 'Podkategorie'},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='profile',
            name='flat_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='house_number',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='profile',
            name='postal_code',
            field=models.CharField(default='', max_length=6),
        ),
        migrations.AddField(
            model_name='profile',
            name='province',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='profile',
            name='street',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='voivodeship',
            field=models.CharField(default='', max_length=32),
        ),
    ]
