# Generated by Django 5.1.4 on 2025-03-06 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rynek', '0007_alter_address_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, default='brak numeru', max_length=20, null=True),
        ),
    ]
