# Generated by Django 5.1.4 on 2025-03-06 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rynek', '0008_alter_profile_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='street',
            new_name='house_and_street_no',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='flat_number',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='house_number',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='province',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='voivodeship',
        ),
    ]
