# Generated by Django 5.1.4 on 2025-03-07 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rynek', '0009_rename_street_profile_house_and_street_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.CharField(default='Polska', max_length=255),
        ),
    ]
