# Generated by Django 5.1.4 on 2025-03-07 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rynek', '0010_profile_country'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
