# Generated by Django 5.1.4 on 2025-03-07 18:31

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rynek', '0011_delete_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_company_name', models.CharField(max_length=255)),
                ('shipping_cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('shipping_time', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name_plural': 'Kurier',
            },
        ),
        migrations.RemoveField(
            model_name='profile',
            name='company_logo',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='nip',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='regon',
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name=django.contrib.auth.models.User)),
                ('company_name', models.CharField(blank=True, max_length=120, null=True)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('nip', models.CharField(blank=True, max_length=20, null=True)),
                ('regon', models.CharField(blank=True, max_length=20, null=True)),
                ('phone', models.CharField(blank=True, default='brak numeru', max_length=20, null=True)),
                ('house_and_street_no', models.CharField(default='', max_length=255)),
                ('city', models.CharField(default='', max_length=120)),
                ('postal_code', models.CharField(default='', max_length=6)),
                ('country', models.CharField(default='Polska', max_length=255)),
                ('payment_methods', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('default_shipping', models.ManyToManyField(blank=True, null=True, related_name='shipping_method', to='rynek.shippingmethod')),
            ],
            options={
                'verbose_name_plural': 'Profile użytkowników',
            },
        ),
    ]
