# Generated by Django 5.1.4 on 2025-03-07 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rynek', '0012_shippingmethod_remove_profile_company_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='default_shipping',
            field=models.ManyToManyField(blank=True, default='', null=True, related_name='shipping_method', to='rynek.shippingmethod'),
        ),
    ]
