# Generated by Django 5.1.4 on 2025-03-07 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rynek', '0013_alter_companyprofile_default_shipping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='default_shipping',
            field=models.ManyToManyField(blank=True, related_name='shipping_method', to='rynek.shippingmethod'),
        ),
    ]
