# Generated by Django 5.1.4 on 2025-03-07 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rynek', '0014_alter_companyprofile_default_shipping'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shippingmethod',
            name='shipping_title',
            field=models.CharField(default='default', max_length=255),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rynek.profile'),
        ),
        migrations.AlterField(
            model_name='shippingmethod',
            name='shipping_time',
            field=models.CharField(max_length=7),
        ),
    ]
