# Generated by Django 5.1.4 on 2025-03-07 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rynek', '0015_product_status_shippingmethod_shipping_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingmethod',
            name='shipping_title',
        ),
    ]
