# Generated by Django 5.1.4 on 2025-03-07 21:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rynek', '0018_alter_shippingmethod_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingmethod',
            name='user',
        ),
        migrations.AddField(
            model_name='shippingmethod',
            name='user',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
