# Generated by Django 5.1.4 on 2025-03-07 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rynek', '0019_remove_shippingmethod_user_shippingmethod_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyprofile',
            name='default_shipping',
        ),
        migrations.DeleteModel(
            name='ShippingMethod',
        ),
    ]
