# Generated by Django 5.1.4 on 2025-03-14 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rynek', '0020_remove_companyprofile_default_shipping_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyProfile',
        ),
    ]
