# Generated by Django 5.1.4 on 2025-03-16 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rynek', '0024_product_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/product/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rynek.product')),
            ],
        ),
    ]
