# Generated by Django 5.1.4 on 2025-03-16 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rynek', '0025_productimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='images',
        ),
    ]
