# Generated by Django 5.1.4 on 2025-03-17 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rynek', '0027_alter_product_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimages',
            old_name='image',
            new_name='images',
        ),
    ]
