# Generated by Django 5.1.4 on 2025-03-19 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rynek', '0028_rename_image_productimages_images'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimages',
            options={'verbose_name_plural': 'Zdjęcia Produktów'},
        ),
    ]
