# Generated by Django 5.1.4 on 2025-03-14 11:02

import django.contrib.auth.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rynek', '0021_delete_companyprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name=django.contrib.auth.models.User)),
                ('company_name', models.CharField(blank=True, max_length=120, null=True)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('nip', models.CharField(blank=True, max_length=20, null=True)),
                ('regon', models.CharField(blank=True, max_length=20, null=True)),
                ('phone', models.CharField(blank=True, default='brak numeru', max_length=20, null=True)),
                ('house_and_street_no', models.CharField(default='', max_length=255)),
                ('city', models.CharField(default='', max_length=120)),
                ('postal_code', models.CharField(default='', max_length=6)),
                ('country', models.CharField(default='Polska', max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rynek.profile')),
            ],
            options={
                'verbose_name_plural': 'Profile Firmowe',
            },
        ),
    ]
