# Generated by Django 5.1.4 on 2025-03-14 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rynek', '0021_delete_companyprofile'),
        ('sprzedawca', '0002_alter_companyprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rynek.profile'),
        ),
    ]
