# Generated by Django 5.1.4 on 2025-03-14 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprzedawca', '0003_alter_companyprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='company_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
