# Generated by Django 5.1.4 on 2025-03-14 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprzedawca', '0004_companyprofile_company_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/company_profile/'),
        ),
    ]
