# Generated by Django 5.1.4 on 2025-03-16 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rynek', '0021_delete_companyprofile'),
        ('sprzedawca', '0008_alter_companyprofile_company_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sprzedawca.companyprofile')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rynek.product')),
            ],
            options={
                'verbose_name_plural': 'Profile Firmowe',
            },
        ),
    ]
