# Generated by Django 5.1.4 on 2025-03-16 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sprzedawca', '0009_companyproduct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyProduct',
        ),
    ]
